### ISSUE TITLE
[proton-tkg] Elden Ring fails to enable online mode due to Easy Anti-Cheat

### ISSUE THREAD

**Issue by Arastais** [Frogging-Family/wine-tkg-git#1135]
<table>
<tr>
<td>Game</td><td>Elden Ring (<code>1245620</code>)</td>
</tr>
<tr>
<td>Graphics Card </td><td>NVIDIA RTX 4070 (Driver <code>550.54.14-4</code>)</td>
</tr>
<tr>
<td>Distro</td><td>Arch (kernel <code>6.7.8.arch1-1</code>)</td>
</tr>
<tr>
<td>Proton-TKG Version</td><td><code>9.3.r1.g91d4974f</code></td>
</tr>
<tr>
<td>Proton-TKG Config</td><td>default <a href="https://github.com/Frogging-Family/wine-tkg-git/blob/master/proton-tkg/proton-tkg.cfg">proton-tkg.cfg</a></td>
</tr>
<tr>
<td>Log</td><td><a href="https://github.com/Frogging-Family/wine-tkg-git/files/14475370/steam-1245620.log">steam-1245620.log</a></td>
</tr>
</table>

Hi, I've recently ran into an issue with Elden Ring related to the anti-cheat (EAC). Basically, the online features of the game are being disabled by EAC. Haven't tested other EAC games.

The game will load properly, along with the universal EAC loading prompt that shows up before the actual game loads (common with many EAC games); However, once in the actual game (specifically the main menu), the game will prompt "Inappropriate activity detected", which I think generally means that EAC couldn't be validated and thus online features have been disabled for the session (i.e. you will not be able to connect to the Elden Ring servers). This prompt is only really expected to occur when your purposely modify the game files (e.g. you install mods), in which EAC is usually manually disabled until you disable the mods and turn EAC back on again.

I have tested the same setup with GE-Proton8-32 and Proton Experimental with no issues - the online features function perfectly. Thus, it seems to be isolated to Proton TKG. Is there a patch that I need that is missing from the default `proton-tkg.cfg` but present in upstream proton?

**Comment by Tk-Glitch** [comment]
The issue comes from mainline based builds. It works fine on Valve based builds.
I have some porting work pending to update some of our current patchsets to their proton 9 versions, which should hopefully fix this.

**Comment by Tk-Glitch** [comment]
Possibly fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/9e6f061d3de833b426a8d4a9391ed5e8d78d046e
I have tested a few EAC games with it successfully (against wine-staging 9.3.r16.gec3dd19d).

**Comment by mak3e** [comment]
I subscribed this thread earlier today due to getting an EAC error with Hunt: Showdown with Proton-TKG 9.3.r16.gec3dd19d so either it's not fixed or it was caused by a separate issue.

![image](https://github.com/Frogging-Family/wine-tkg-git/assets/12019476/687f7b44-081d-4071-b4b2-56f43e8c0be5)

**Comment by Tk-Glitch** [comment]
With a fresh build I assume?

**Comment by mak3e** [comment]
I used the most recent nightly build provided by the project's Github CI

This one to be exact:
https://github.com/Frogging-Family/wine-tkg-git/actions/runs/8201327374

**Comment by Tk-Glitch** [comment]
That build is too old to have the fix. You'll need to either build yourself or wait for the next CI run.
![Screenshot_20240308_211600](https://github.com/Frogging-Family/wine-tkg-git/assets/741977/729e96a8-78ac-42df-a22b-4dde9c9da6b0)
Just tested hunt against the changes above, with success.

**Comment by mak3e** [comment]
Ah, I didn't realize the commit was made today due to the version number being the same. My bad.

I tried to build it earlier but the build failed and I didn't have time to investigate. I'll try again now.

**Comment by Arastais** [comment]
I still have this issue with Elden Ring when using [Wine Master Arch CI #1227](https://github.com/Frogging-Family/wine-tkg-git/actions/runs/8209227242) (which is built against wine-staging 9.3.r16.gec3dd19d)

**Comment by Tk-Glitch** [comment]
I have updated our BE/EAC support patches. Hopefully will fix your Elden Ring issue.

**Comment by IlChitarrista** [comment]
I just tested the latest build, can confirm it does fix EAC in Elden Ring.
Thanks :smile:
