### ISSUE TITLE
Can't login in Battlenet with Proton-tkg

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#1327]
Hi! Everything works fine with the inbuilt Steam's vanilla Proton Experimental. But with TKG the LOGIN button never appears, instead all I see is an infinitely long time spinning Battlenet logo signifying loading. This behaviour happens if I use FSYNC. But no logo even rotates if I try to use NTSYNC, because then the Battlenet application always hangs completely.
[last_build_config.log](https://github.com/user-attachments/files/17879079/last_build_config.log)
[prepare.log](https://github.com/user-attachments/files/17879080/prepare.log)
[battlenet_log.txt](https://github.com/user-attachments/files/17879159/battlenet_log.txt)
![Screenshot From 2024-11-23 13-31-58](https://github.com/user-attachments/assets/389aa26b-c20e-403b-b823-e1b9c520bd57)

**Comment by AllenTzul** [comment]
Maybe you can try applying this patch [proton_battleye.patch](https://raw.githubusercontent.com/SingleInfiniteLoop/wine-tkg-git/78cea96f16139c5bed24593899c4defc8bfc8383/wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton_battleye/proton_battleye.patch).

**Comment by Artewar67** [comment]
Looks like ntdll-WRITECOPY patch stop working properly on newer version. I tested and this occurs regardless of the synchronization method selected, including server-side. I also tested standard wine and wine-staging from arch linux repository and same thing

**Comment by Artewar67** [comment]
[wine-tkg-userpatches.zip](https://github.com/user-attachments/files/17882775/wine-tkg-userpatches.zip)
Try these patches. download them and extract them into the wine-tkg-userpatch folder. Also set _protonify=false and clean the prefix

**Comment by Kerrung** [comment]
> [wine-tkg-userpatches.zip](https://github.com/user-attachments/files/17882775/wine-tkg-userpatches.zip) Try these patches. download them and extract them into the wine-tkg-userpatch folder. Also set _protonify=false and clean the prefix

@Artewar67 I have just tested with your patches and fresh prefix, but have not changes, it have not helped.

**Comment by Artewar67** [comment]
I found out that you have to clean the prefix before testing. Now wine from arch linux repository no longer has this bug and I'm trying to figure out what wine-tkg patch is causing it

**Comment by Artewar67** [comment]
I found out that you have battle.net crashing and you need staging patches for that. You need to set _use_staging=true. I have also if do not apply staging, it crashes on installation at 45% and at startup if i install it with wine-staging before that.

**Comment by Artewar67** [comment]
> [wine-tkg-userpatches.zip](https://github.com/user-attachments/files/17882775/wine-tkg-userpatches.zip) Try these patches. download them and extract them into the wine-tkg-userpatch folder. Also set _protonify=false and clean the prefix

You also don't need this patchset. I thought the ntdll-WRITECOPY patch was broken until I tried cleaning the prefix

**Comment by Kerrung** [comment]
> I found out that you have battle.net crashing and you need staging patches for that. You need to set _use_staging=true. I have also if do not apply staging, it crashes on installation at 45% and at startup if i install it with wine-staging before that.
@Artewar67 
1. If everything is as you say is true, then why does this problem not exist if I use vanilla Proton from Steam?
2. Unfortunately, I had to stop using Staging because it causes a regression in Mass Effect Legendary Edition when using Winewayland. When mouse pointer moving over menu items, they should be highlighted, but they are not, causing menu items to have to be clicked twice if I want to choose it. Also when selecting weapons or abilities during combat, I also have to double-click to make it work. I'm going to write about this bug on the Wine's website.

**Comment by Artewar67** [comment]
>If everything is as you say is true, then why does this problem not exist if I use vanilla Proton from Steam?

Proton may contain changes taken from staging but also a bunch of code modifications that are not found in standard wine. For example I had to play one game through Proton-GE because videos don't work in wine and it has its own Bug report in Wine Bugzilla: https://bugs.winehq.org/show_bug.cgi?id=50277

**Comment by Artewar67** [comment]
winegstreamer has been heavily modified in proton and also contains a new media_source implementation. The developers tried to implement this in standard wine but it was rejected.

**Comment by Kerrung** [comment]
> > If everything is as you say is true, then why does this problem not exist if I use vanilla Proton from Steam?
> 
> Proton may contain changes taken from staging but also a bunch of code modifications that are not found in standard wine. For example I had to play one game through Proton-GE because videos don't work in wine and it has its own Bug report in Wine Bugzilla: https://bugs.winehq.org/show_bug.cgi?id=50277

And so, what we should to do next now?

**Comment by Artewar67** [comment]
I'll try to find the staging patches need for Battle.net.

**Comment by Artewar67** [comment]
I found out that it was a bug in the ntsync5 patch for mainline and protonify. This commit should fix it

**Comment by Kerrung** [comment]
@Artewar67 now Battlenet hang no more happens with NTSYNC since https://github.com/Frogging-Family/wine-tkg-git/commit/cadda7ef00fc9db5b90d4cc376a151766421d46a, but I still can't login.

**Comment by Artewar67** [comment]
[0011-kernelbase-Handle-NULL-old_prot-parameter-in-Virtual.txt](https://github.com/user-attachments/files/17939441/0011-kernelbase-Handle-NULL-old_prot-parameter-in-Virtual.txt)
Try this patch (rename format to mypatch and put file in wine-tkg-userpatch)

**Comment by Kerrung** [comment]
> [0011-kernelbase-Handle-NULL-old_prot-parameter-in-Virtual.txt](https://github.com/user-attachments/files/17939441/0011-kernelbase-Handle-NULL-old_prot-parameter-in-Virtual.txt) Try this patch (rename format to mypatch and put file in wine-tkg-userpatch)

@Artewar67 with this patch now i can login easy, but now appear a new issue - Battlenet want to install itself update everytime, but have not installed it if I press a button to install it and restart BN, then every time I see a update available. Should I open a new separate issue?

**Comment by Artewar67** [comment]
With this commit you no longer need special patch for battle.net

>@Artewar67 with this patch now i can login easy, but now appear a new issue - Battlenet want to install itself update everytime, but have not installed it if I press a button to install it and restart BN, then every time I see a update available. Should I open a new separate issue?

I think yes you can open a new issue since we have solved the main problem of this issue.

**Comment by Kerrung** [comment]
> With this commit you no longer need special patch for battle.net
> 
> > @Artewar67 with this patch now i can login easy, but now appear a new issue - Battlenet want to install itself update everytime, but have not installed it if I press a button to install it and restart BN, then every time I see a update available. Should I open a new separate issue?
> 
> I think yes you can open a new issue since we have solved the main problem of this issue.

@Artewar67  OK, thank you. But I think we will have solved the main problem of this issue your patch will bee added to this repo etc.

**Comment by Thaodan** [comment]
Does Battle.net still work, does it work without ESYNC too?

**Comment by Kerrung** [comment]
> Does Battle.net still work, does it work without ESYNC too?

@Thaodan I just tested BN specifically for you and it ran with no problems. I use NTSYNC, but I don't use ESYNC. The Blizzard adverts don't work. Instead it just says ‘Sorry, something went wrong...’.
Also the StarCraft2 I have previously installed tries to install an update but it fails to do so, but without it the game refuses to launch. I don't know if this is related to the fact that I'm not using Staging patches right now. I also haven't tried launching through Steam's official Proton yet.

![Image](https://github.com/user-attachments/assets/4b0402e5-9342-43f9-9eb4-de361a533c87)

**Comment by Kerrung** [comment]
> For me it doesn't work the ui freezes crash with: `0024:err:virtual:virtual_setup_exception stack overflow 2688 bytes addr 0x79176e43 stack 0x500580 (0x500000-0x501000-0x600000)`
> 
> My build config here: https://build.opensuse.org/projects/home:Thaodan:emulators/packages/wine/files/customization.cfg?expand=1

@Thaodan I think you should open a new issue. This one is about broken login it Battlenet, but not about freezes.

**Comment by Thaodan** [comment]
> > For me it doesn't work the ui freezes crash with: `0024:err:virtual:virtual_setup_exception stack overflow 2688 bytes addr 0x79176e43 stack 0x500580 (0x500000-0x501000-0x600000)`
> > My build config here: https://build.opensuse.org/projects/home:Thaodan:emulators/packages/wine/files/customization.cfg?expand=1
> 
> [@Thaodan](https://github.com/Thaodan) I think you should open a new issue. This one is about broken login it Battlenet, but not about freezes.

Done #1492.
