### ISSUE TITLE
ntsync5-staging.patch failed (rebase?)

### ISSUE THREAD

**Issue by nokia8801** [Frogging-Family/wine-tkg-git#1468]
Perhaps a rebase is needed?

[prepare.log](https://github.com/user-attachments/files/20100268/prepare.log)

```
...
  -> Creating working copy of wine-staging-git git repo...
Cloning into 'wine-staging-git'...
done.
==> Starting prepare()...
==> WARNING: Disable broken winedevice-Default_Drivers patchset on staging 6912feaf
  -> Changing wine HEAD to the wine-staging base commit...
  -> Using upstream-commit file
HEAD is now at d8a271c053b winegstreamer: Only align the first plane in gst_video_info_align.
==> WARNING: Hotfix: Fix for Riot Client updates
==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
==> WARNING: Hotfix: Fix NosTale mouse bug
  -> cherry picking...
  -> Hotfixing...
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches using staging/patchinstall.py... 
     Staging overrides used, if any: -W winedevice-Default_Drivers
  -> Applying enable_dynamic_wow64_def.patch
  -> Applying LAA-unix-staging-wow64.patch
  -> Applying ntsync-config.h.in-alt.patch
  -> Applying ntsync5-staging.patch
==> ERROR: Patch application has failed. The error was logged to /tmp/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
==> Removing installed dependencies...
```

**Comment by mikeserv-git** [comment]
Yes, it's trivial to fix at this time (but still a pain in the ass and it's going to take time for them to fix). It's mostly just context that's changed.

I have fixed them for myself, the ones I use that were failing. ntsync5-staging-protonify.patch for proton-tkg with upstream wine for Steam and  ntsync5-staging.patch for wine-tkg that I use for Lutris.

You can replace the failing hunks in the .patch files yourself, whichever you are using.

For ntsync5-staging.patch

```
@@ -6912,14 +6912,14 @@
     struct resume_process_reply resume_process_reply;
     struct get_next_process_reply get_next_process_reply;
     struct get_next_thread_reply get_next_thread_reply;
-    struct create_esync_reply create_esync_reply;
-    struct open_esync_reply open_esync_reply;
-    struct get_esync_fd_reply get_esync_fd_reply;
-    struct esync_msgwait_reply esync_msgwait_reply;
     struct set_keyboard_repeat_reply set_keyboard_repeat_reply;
-    struct get_esync_apc_fd_reply get_esync_apc_fd_reply;
+    struct get_linux_sync_device_reply get_linux_sync_device_reply;
+    struct get_linux_sync_obj_reply get_linux_sync_obj_reply;
+    struct select_inproc_queue_reply select_inproc_queue_reply;
+    struct unselect_inproc_queue_reply unselect_inproc_queue_reply;
+    struct get_inproc_alert_event_reply get_inproc_alert_event_reply;
 };
 
-#define SERVER_PROTOCOL_VERSION 866
+#define SERVER_PROTOCOL_VERSION 869
```

For ntsync5-staging-protonify.patch

```
@@ -6912,12 +6912,12 @@
     struct resume_process_reply resume_process_reply;
     struct get_next_process_reply get_next_process_reply;
     struct get_next_thread_reply get_next_thread_reply;
-    struct create_esync_reply create_esync_reply;
-    struct open_esync_reply open_esync_reply;
-    struct get_esync_fd_reply get_esync_fd_reply;
-    struct esync_msgwait_reply esync_msgwait_reply;
     struct set_keyboard_repeat_reply set_keyboard_repeat_reply;
-    struct get_esync_apc_fd_reply get_esync_apc_fd_reply;
+    struct get_linux_sync_device_reply get_linux_sync_device_reply;
+    struct get_linux_sync_obj_reply get_linux_sync_obj_reply;
+    struct select_inproc_queue_reply select_inproc_queue_reply;
+    struct unselect_inproc_queue_reply unselect_inproc_queue_reply;
+    struct get_inproc_alert_event_reply get_inproc_alert_event_reply;
 };

-#define SERVER_PROTOCOL_VERSION 865
+#define SERVER_PROTOCOL_VERSION 869
```

Alternatively, I'm attaching my working patches renamed to .patch.txt (I don't think it allows .patch for uploads)

[ntsync5-staging.patch.txt](https://github.com/user-attachments/files/20112901/ntsync5-staging.patch.txt)
[ntsync5-staging-protonify.patch.txt](https://github.com/user-attachments/files/20112902/ntsync5-staging-protonify.patch.txt)

**Comment by Artewar67** [comment]
After #1470 should now work

**Comment by nokia8801** [comment]
Well the patch now applies, thanks, but I still can't compile because of #1466.

**Comment by Artewar67** [comment]
Now ntsync patches for staging rebased and should work
