### ISSUE TITLE
(Not a duplicate) Patch Application Failed.

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/wine-tkg-git#1656]
The patches failing for me are not the same as the other recent reports. 

Relevant section of `prepare.log`:

```
proton-tkg.patch -- ( Using Steam-specific Proton-tkg patches 2/3 )
patching file server/main.c
Hunk #1 succeeded at 44 (offset 2 lines).
patching file dlls/ntdll/unix/thread.c
Hunk #1 succeeded at 61 with fuzz 2 (offset 18 lines).
Hunk #2 succeeded at 1531 (offset 1184 lines).
Hunk #3 succeeded at 1562 (offset 1183 lines).
patching file dlls/dwrite/font.c
Hunk #1 succeeded at 1251 (offset 511 lines).
patching file dlls/msctf/msctf.c
Hunk #1 succeeded at 67 (offset -2 lines).
Hunk #2 succeeded at 393 (offset -3 lines).
Hunk #3 succeeded at 432 (offset -3 lines).
Hunk #4 succeeded at 550 (offset -6 lines).
Hunk #5 succeeded at 586 (offset -30 lines).
patching file dlls/msctf/msctf_internal.h
Hunk #1 succeeded at 36 with fuzz 2 (offset 1 line).
patching file dlls/msctf/threadmgr.c
Hunk #5 succeeded at 211 with fuzz 2.
Hunk #8 succeeded at 1400 (offset 8 lines).
Hunk #9 succeeded at 1416 (offset 8 lines).
Hunk #10 succeeded at 1432 (offset 8 lines).
patching file programs/dxdiag/main.c
Hunk #1 succeeded at 72 (offset 1 line).
patching file programs/dxdiag/output.c
Hunk #1 succeeded at 149 with fuzz 1 (offset -20 lines).
Hunk #2 succeeded at 211 (offset -20 lines).
patching file tools/makedep.c
Hunk #1 succeeded at 3650 with fuzz 1 (offset 405 lines).
patching file dlls/dxgi/adapter.c
Hunk #1 succeeded at 171 with fuzz 1 (offset 10 lines).
patching file dlls/dsound/dsound.c
Hunk #2 succeeded at 136 (offset -1 lines).
Hunk #3 succeeded at 1127 (offset 1 line).
patching file dlls/dsound/dsound_private.h
Hunk #1 succeeded at 209 (offset 7 lines).
patching file dlls/dsound/primary.c
Hunk #1 succeeded at 24 with fuzz 1.
Hunk #2 succeeded at 108 (offset -3 lines).
Hunk #3 succeeded at 194 (offset -3 lines).
patching file dlls/dxgi/adapter.c
Hunk #1 succeeded at 210 (offset 10 lines).
patching file dlls/ntdll/unix/file.c
Hunk #1 succeeded at 3705 (offset 112 lines).
patching file server/fd.c
Hunk #1 succeeded at 2108 (offset 29 lines).
patching file server/file.c
Hunk #1 succeeded at 156 (offset 9 lines).
patching file server/file.h
Hunk #2 succeeded at 87 with fuzz 1 (offset 4 lines).
patching file dlls/ntdll/unix/virtual.c
Hunk #1 succeeded at 5213 with fuzz 2 (offset 1788 lines).
patching file dlls/d3d10core/d3d10core_main.c
Hunk #1 succeeded at 29 with fuzz 2.
patching file dlls/dxgi/dxgi_main.c
Hunk #1 succeeded at 103 (offset -3 lines).
Hunk #2 succeeded at 114 with fuzz 1 (offset -3 lines).
patching file dlls/kernelbase/file.c
Hunk #1 succeeded at 42 (offset 1 line).
Hunk #2 succeeded at 702 with fuzz 1 (offset 268 lines).
Hunk #3 succeeded at 879 (offset 351 lines).
Hunk #4 succeeded at 897 (offset 351 lines).
patching file dlls/kernelbase/file.c
Hunk #1 succeeded at 715 (offset 268 lines).
patching file dlls/wbemprox/builtin.c
Hunk #1 succeeded at 1628 (offset 447 lines).
Hunk #2 succeeded at 1674 (offset 447 lines).
Hunk #3 succeeded at 1753 with fuzz 1 (offset 446 lines).
Hunk #4 succeeded at 1956 (offset 315 lines).
Hunk #5 succeeded at 3215 with fuzz 2 (offset 321 lines).
Hunk #6 succeeded at 4230 with fuzz 1 (offset 755 lines).
Hunk #7 succeeded at 4490 (offset 750 lines).
Hunk #8 succeeded at 4858 with fuzz 2 (offset 903 lines).
patching file dlls/ws2_32/protocol.c
Hunk #1 succeeded at 167 (offset -65 lines).
patching file dlls/ws2_32/unixlib.c
Hunk #1 succeeded at 988 (offset 119 lines).
patching file server/queue.c
Hunk #1 succeeded at 1970 with fuzz 2 (offset 329 lines).
patching file configure
Hunk #1 succeeded at 1686 (offset -80 lines).
Hunk #2 succeeded at 23374 (offset 1794 lines).
patching file configure.ac
Hunk #1 succeeded at 3542 (offset -455 lines).
patching file programs/dotnetfx35/Makefile.in
patching file programs/dotnetfx35/main.c
patching file dlls/winex11.drv/x11drv_main.c
Hunk #1 succeeded at 72 with fuzz 2 (offset -4 lines).
patching file programs/winecfg/x11drvdlg.c
Hunk #1 succeeded at 138 with fuzz 2 (offset 15 lines).
patching file dlls/kernelbase/file.c
patching file dlls/vulkan-1/Makefile.in
Hunk #1 succeeded at 2 with fuzz 2.
patching file loader/wine.inf.in
Hunk #5 succeeded at 224 (offset -27 lines).
Hunk #6 succeeded at 643 (offset 41 lines).
patching file dlls/kernel32/kernel32.spec
Hunk #1 succeeded at 778 with fuzz 1 (offset 13 lines).
patching file dlls/kernelbase/kernelbase.spec
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file dlls/kernelbase/kernelbase.spec.rej
patching file dlls/kernelbase/version.c
Hunk #1 succeeded at 37 (offset -2 lines).
Hunk #2 succeeded at 161 (offset 5 lines).
Hunk #3 succeeded at 1769 (offset 84 lines).
patching file include/appmodel.h
Hunk #1 succeeded at 89 (offset 7 lines).
patching file dlls/kernel32/kernel32.spec
Hunk #1 succeeded at 1172 (offset 20 lines).
patching file dlls/kernelbase/kernelbase.spec
Hunk #1 succeeded at 1051 (offset 39 lines).
patching file dlls/kernelbase/version.c
Hunk #1 succeeded at 1681 (offset 84 lines).
Hunk #2 succeeded at 1781 (offset 84 lines).
patching file include/appmodel.h
Hunk #1 succeeded at 91 (offset 7 lines).
patching file dlls/kernel32/kernel32.spec
Hunk #1 FAILED at 768.
1 out of 1 hunk FAILED -- saving rejects to file dlls/kernel32/kernel32.spec.rej
patching file dlls/kernelbase/kernelbase.spec
Hunk #1 FAILED at 601.
1 out of 1 hunk FAILED -- saving rejects to file dlls/kernelbase/kernelbase.spec.rej
patching file dlls/kernelbase/version.c
Hunk #1 succeeded at 1923 (offset 84 lines).
patching file include/appmodel.h
Hunk #1 succeeded at 89 (offset 7 lines).
patching file dlls/kernel32/kernel32.spec
Hunk #1 FAILED at 775.
1 out of 1 hunk FAILED -- saving rejects to file dlls/kernel32/kernel32.spec.rej
patching file dlls/kernelbase/kernelbase.spec
Hunk #1 FAILED at 631.
1 out of 1 hunk FAILED -- saving rejects to file dlls/kernelbase/kernelbase.spec.rej
patching file dlls/kernelbase/version.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file dlls/kernelbase/version.c.rej
patching file dlls/dxgi/factory.c
Hunk #1 succeeded at 26 (offset -3 lines).
Hunk #2 succeeded at 55 (offset -3 lines).
Hunk #3 succeeded at 65 (offset -3 lines).
patching file dlls/dxgi/swapchain.c
Hunk #1 succeeded at 224 (offset -8 lines).
Hunk #2 succeeded at 301 with fuzz 1 (offset -24 lines).
Hunk #3 succeeded at 700 (offset 3 lines).
patching file dlls/dxgi/dxgi_main.c
Hunk #1 succeeded at 53 (offset -3 lines).
Hunk #2 succeeded at 79 (offset -3 lines).
patching file dlls/dxgi/dxgi_private.h
Hunk #1 succeeded at 214 with fuzz 2 (offset 5 lines).
patching file dlls/dxgi/factory.c
Hunk #2 succeeded at 1059 with fuzz 1.
Hunk #3 succeeded at 1129 (offset 1 line).
patching file dlls/msvcrt/math.c
Hunk #1 succeeded at 44 (offset 2 lines).
Hunk #2 succeeded at 66 (offset 1 line).
Hunk #3 succeeded at 72 (offset -1 lines).
patching file dlls/msvcrt/msvcrt.h
Hunk #1 succeeded at 67 (offset 35 lines).
patching file dlls/msvcrt/string.c
Hunk #1 succeeded at 3040 (offset 318 lines).
Hunk #2 succeeded at 3182 with fuzz 2 (offset 330 lines).
Hunk #3 succeeded at 3272 (offset 335 lines).
patching file dlls/msvcrt/string.c
Hunk #1 succeeded at 3224 (offset 330 lines).
Hunk #2 succeeded at 3299 (offset 335 lines).
patching file dlls/msvcrt/string.c
Hunk #1 succeeded at 3231 (offset 330 lines).
patching file dlls/kernelbase/debug.c
Hunk #1 succeeded at 1771 (offset 246 lines).
patching file configure.ac
Hunk #1 succeeded at 2486 (offset -139 lines).
patching file dlls/audioses/Makefile.in
patching file dlls/audioses/audioses.spec
patching file dlls/winex11.drv/xrandr.c
Hunk #1 succeeded at 36 (offset 8 lines).
Hunk #2 succeeded at 453 (offset 78 lines).
Hunk #3 succeeded at 503 (offset 78 lines).

proton-steam-bits-non-protonify.patch -- ( Using Steam-specific Proton-tkg patches (staging) 3/3 Non protonify version )
patching file loader/wine.inf.in
Hunk #1 succeeded at 71 (offset 1 line).
Hunk #2 succeeded at 100 with fuzz 2 (offset 2 lines).
Hunk #3 succeeded at 125 (offset 4 lines).
Hunk #4 succeeded at 133 (offset 4 lines).
Hunk #5 succeeded at 1239 (offset -2632 lines).
patching file dlls/kernelbase/process.c
Hunk #1 succeeded at 1093 with fuzz 2 (offset 79 lines).
patching file dlls/advapi32/advapi.c
patching file dlls/shell32/shellpath.c
Hunk #1 FAILED at 4369.
1 out of 1 hunk FAILED -- saving rejects to file dlls/shell32/shellpath.c.rej
patching file loader/wine.inf.in
Hunk #1 FAILED at 181.
Hunk #2 succeeded at 522 (offset -92 lines).
1 out of 2 hunks FAILED -- saving rejects to file loader/wine.inf.in.rej
patching file loader/wine.inf.in
Hunk #1 succeeded at 526 (offset -93 lines).
patching file dlls/ntdll/unix/env.c
Hunk #1 succeeded at 344 (offset 3 lines).
patching file configure
Hunk #1 succeeded at 1767 (offset 21 lines).
Hunk #2 succeeded at 23468 (offset 3154 lines).
patching file configure.ac
Hunk #1 succeeded at 3638 (offset -360 lines).
patching file loader/wine.inf.in
Hunk #1 FAILED at 3598.
1 out of 1 hunk FAILED -- saving rejects to file loader/wine.inf.in.rej
patching file dlls/winex11.drv/window.c
Hunk #1 succeeded at 1111 (offset 256 lines).
patching file dlls/dbghelp/dwarf.c
Hunk #1 succeeded at 4319 (offset 157 lines).
patching file programs/winedbg/tgt_active.c
Hunk #1 succeeded at 917 (offset -48 lines).
patching file programs/winedbg/debugger.h
Hunk #1 succeeded at 311 (offset 28 lines).
patching file programs/winedbg/tgt_active.c
Hunk #2 succeeded at 829 (offset 43 lines).
Hunk #3 succeeded at 963 (offset -48 lines).
patching file programs/winedbg/winedbg.c
patching file loader/wine.inf.in
Hunk #1 succeeded at 416 (offset -124 lines).
patching file loader/wine.inf.in
Hunk #1 succeeded at 303 with fuzz 2 (offset -14 lines).
patching file programs/wineboot/wineboot.c
Hunk #1 succeeded at 1496 with fuzz 1 (offset 461 lines).
Hunk #2 succeeded at 1504 with fuzz 2 (offset 452 lines).
Hunk #3 succeeded at 1653 with fuzz 2 (offset 524 lines).
Hunk #4 succeeded at 1674 with fuzz 2 (offset 533 lines).
patching file loader/wine.inf.in
Hunk #1 succeeded at 303 with fuzz 2 (offset -27 lines).
patching file loader/wine.inf.in
Hunk #1 succeeded at 72 (offset -2 lines).
Hunk #2 succeeded at 102 with fuzz 2 (offset -1 lines).
Hunk #3 succeeded at 136 (offset -11 lines).
Hunk #4 succeeded at 1265 (offset -2999 lines).
```

proton-tkg.patch and proton-steam-bits-non-protonify.patch are the culprits.

**Comment by Artewar67** [comment]
`proton-steam-bits-non-protonify.patch` is now fixed, however i not able to reproduce patch fail with `proton-tkg.patch`

**Comment by gardotd426** [comment]
> `proton-steam-bits-non-protonify.patch` is now fixed, however i not able to reproduce patch fail with `proton-tkg.patch`

It's indeed not fixed:

```
proton-steam-bits-non-protonify.patch -- ( Using Steam-specific Proton-tkg patches (staging) 3/3 Non protonify version )
patching file loader/wine.inf.in
Hunk #1 succeeded at 71 (offset 1 line).
Hunk #2 succeeded at 100 with fuzz 2 (offset 2 lines).
Hunk #3 FAILED at 121.
Hunk #4 succeeded at 132 (offset 4 lines).
Hunk #5 succeeded at 1238 (offset -2632 lines).
1 out of 5 hunks FAILED -- saving rejects to file loader/wine.inf.in.rej
patching file dlls/kernelbase/process.c
Hunk #1 succeeded at 1093 with fuzz 2 (offset 79 lines).
patching file dlls/advapi32/advapi.c
patching file dlls/shell32/shellpath.c
Hunk #1 succeeded at 3030 (offset -1339 lines).
patching file loader/wine.inf.in
Hunk #1 FAILED at 181.
Hunk #2 succeeded at 521 (offset -93 lines).
1 out of 2 hunks FAILED -- saving rejects to file loader/wine.inf.in.rej
```

`proton-tkg.patch` still fails as well.

**Comment by gardotd426** [comment]
```
Switched to a new branch 'makepkg'
 => Cleaning wine source code tree...
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 ==> WARNING: Hotfix: Fix NosTale mouse bug
 ==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
 => cherry picking...
 => Hotfixing...
 => ## Applying reverting hotfix for wine-mainline: d4259ac8e93.myearlyrevert
 => Applying LAA-unix-wow64.patch
 => Applying proton-tkg-steamclient-swap-wow64.patch
 => Applying ge-wayland.patch
 => Applying proton-tkg.patch
 ===> ERROR: Patch application has failed. The error was logged to /home/matt/dev/wine-tkg/wine-tkg-git/prepare.log for your convenience.
 => Applying proton-steam-bits-non-protonify.patch
 ===> ERROR: Patch application has failed. The error was logged to /home/matt/dev/wine-tkg/wine-tkg-git/prepare.log for your convenience.
 => Applying proton-tkg-additions.patch
 ==> WARNING: NTsync was already implemented in Wine 10.16. Don't applying fastsync patches
 => Applying proton-win10-default.patch
 => ## Applying hotfix for plain-wine: Return_nt_filename_and_resolve_DOS_drive_path.mypatch
 => ## Applying hotfix for plain-wine: a608ef1.mypatch
 => ## Applying hotfix for plain-wine: nostale_mouse_fix.mypatch
 => ## Applying hotfix for plain-wine: opencl-fixup.mypatch
 => Applying wine-tkg.patch
```

**Comment by Tk-Glitch** [comment]
Fixed for a while. Closing.
