### ISSUE TITLE
Can't generate default prefix during compiling Proton-tkg

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/wine-tkg-git#414]
Arch Linux;
Proton-tkg commit (makepkg) : 2ba773a3bf9e7d03f8241741357b3b67d61000bc
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6642039/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6642040/prepare.log)
![Screenshot from 2021-06-12 13-36-52](https://user-images.githubusercontent.com/36989404/121773778-895ce980-cb97-11eb-8db0-f9ac3a3ee052.png)

**Comment by Tk-Glitch** [comment]
I need your `proton-tkg.log`

**Comment by Kerrung** [comment]
> I need your `proton-tkg.log`

[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6642862/proton-tkg.log)

**Comment by Tk-Glitch** [comment]
```
wine: Unhandled illegal instruction at address 00000001400068E2 (thread 002c), starting debugger...
```
Hmm.. I'd say it's probably fixed by https://github.com/Frogging-Family/wine-tkg-git/commit/68190c3dfab48e360d6833b894cd340cdf556e31

**Comment by Kerrung** [comment]
> ```
> wine: Unhandled illegal instruction at address 00000001400068E2 (thread 002c), starting debugger...
> ```
> 
> Hmm.. I'd say it's probably fixed by [68190c3](https://github.com/Frogging-Family/wine-tkg-git/commit/68190c3dfab48e360d6833b894cd340cdf556e31)

I just retested with 56bd2967acd0882445c49643dceeb0debe05d44d, but didn't see any changes during prefix generation, still crashes.
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6642993/proton-tkg.log)
[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6642994/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6642995/prepare.log)
![Screenshot from 2021-06-12 13-36-52](https://user-images.githubusercontent.com/36989404/121790580-42eca680-cbfa-11eb-8f89-9fb2b9f53ef1.png)

**Comment by Kerrung** [comment]
It's still an issue with 1626cf83facc1a9d6facf024294f471c523a1384

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6655725/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6655726/prepare.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6655728/proton-tkg.log)

**Comment by Kerrung** [comment]
It's still an issue with 1626cf83facc1a9d6facf024294f471c523a1384

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/6655725/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/6655726/prepare.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/6655728/proton-tkg.log)

wine: created the configuration directory '/run/media/user/Arch-Home/user/Other/proton-tkg/src/proton_tkg_makepkg/files/share/default_pfx'
wineserver: using server-side synchronization.
wine: Unhandled illegal instruction at address 00000001400068E2 (thread 002c), starting debugger...
wine: could not load kernel32.dll, status c0000135
Traceback (most recent call last):
  File "/run/media/user/Arch-Home/user/Other/proton-tkg/src/proton_template/default_pfx.py", line 118, in <module>
    make_default_pfx(sys.argv[1], sys.argv[2], None)
  File "/run/media/user/Arch-Home/user/Other/proton-tkg/src/proton_template/default_pfx.py", line 105, in make_default_pfx
    subprocess.run(runtime_args + ["/bin/bash", "-c",
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/bash', '-c', '/run/media/user/Arch-Home/user/Other/proton-tkg/src/proton_tkg_makepkg/files/bin/wine wineboot && /run/media/user/Arch-Home/user/Other/proton-tkg/src/proton_tkg_makepkg/files/bin/wineserver -w']' returned non-zero exit status 53.
wineserver: could not save registry branch to system.reg : No such file or directory
wineserver: could not save registry branch to user.reg : No such file or directory

**Comment by Kerrung** [comment]
I was able to successfully generate the prefix and create the package when I removed all used by default _community_patches="" from proton-tkg.cfg. Therefore, I am now sure that one or more _community_patches="" is the cause of this problem. Previously, they did not cause such problems, but, apparently, after one of the Wine updates, it now began to require a rebase to fix this problem. It is possible to find out which used by default _community_patches="" are causing this problem if try to compile Proton-tkg several times, each time using only one of these, but it will take a lot of time.
And since these _community_patches="" are now used by default, I will not close this issue until this is fixed.

**Comment by Kerrung** [comment]
I was able to successfully generate the prefix and create the package when I removed all used by default _community_patches="" from proton-tkg.cfg. Therefore, I am now sure that one or more _community_patches="" is the cause of this problem. Previously, this used by default _community_patches="" did not cause such problems, but, apparently, after one of the Wine updates, it now began to require a rebase to fix this problem. It is possible to find out which used by default _community_patches="" are causing this problem if try to compile Proton-tkg several times, each time using only one of these, but it will take a lot of time.
And since these _community_patches="" are now used by default, I will not close this issue until this is fixed.

**Comment by Kerrung** [comment]
I've tried compiling Proton-tkg using only one of the _community_patches="" at a time to find out which ones are causing the problem. I figured out that [0002-proton_QPC.mypatch](https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/0002-proton_QPC.mypatch) is causing the prefix generation to crash because I just checked compile with it and without it the compilation is complete successfully. Yes, this patch is not used by default, therefore, it turned out to be inappropriate for what I had previously argued that one of the default patches is to blame for this problem. And so, as a result, a rebase or a fix for [0002-proton_QPC.mypatch](https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/0002-proton_QPC.mypatch) is required.

**Comment by Kerrung** [comment]
I've just tried compiling Proton-tkg using only one of the _community_patches="" at a time to find out which ones are causing the problem. I figured out that [0002-proton_QPC.mypatch](https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/0002-proton_QPC.mypatch) is causing the prefix generation to crash because I just checked compile with it and without it the compilation is complete successfully. Yes, this patch is not used by default, therefore, it turned out it was untrue what I had previously argued that one of the using by default patches is to blame for this problem. And so, as a result, a rebase or a fix for [0002-proton_QPC.mypatch](https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/0002-proton_QPC.mypatch) is only required.

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue on my machine. I assume your platform might have unstable timers. Since this is a hardware issue, I'm marking as wontfix for now. I'll let Rémi know about this.

**Comment by Kerrung** [comment]
> I cannot reproduce the issue on my machine. I assume your platform might have unstable timers. Since this is a hardware issue, I'm marking as wontfix for now. I'll let Rémi know about this.

I using linux-tkg with this cfg:
[customization.zip](https://github.com/Frogging-Family/wine-tkg-git/files/6681181/customization.zip)
