### ISSUE TITLE
Error hotfixing when building latest staging.

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/wine-tkg-git#795]
```
  -> Hotfixing...
error: could not revert 13a04cdf519... win32u: Use syscall interface for NtUserGetRawInputBuffer.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
==> ERRO: Patch application has failed. The error was logged to /mnt/archlinux/CCACHE/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
  -> To use the last known good mainline version, please set _plain_version="" in your .cfg
  -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")

```
[prepare.log](https://pastebin.com/UmWNhkwd)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/49ecac56975f3d476b66ed23587d0581ceebdbb0

**Comment by rizzini** [comment]
It's still happening to me. The same exact error.
[prepare.log](https://pastebin.com/YMHgQEDp)

Just in case:
[wine-tkg.cfg](https://github.com/rizzini/Dotfiles/blob/master/.config/frogminer/wine-tkg.cfg)
[advanced-customization.cfg](https://github.com/rizzini/Dotfiles/blob/master/.config/frogminer/advanced-customization.cfg)

**Comment by rizzini** [comment]
My bad. I didn't clone the repository after you fixed it.
