### ISSUE TITLE
Games not running - steam.exe.so

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#824]
Tried with multiple Games and getting the same issue, enabling logging, I see this at the end of the log 
```ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
3012.658:0148:014c:err:module:open_builtin_so_file failed to load .so lib "/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.14.r1.gf2648a9a/files/lib/wine/i386-unix/steam.exe.so"
wine: failed to start L"C:\\Program Files (x86)\\Steam\\steam.exe"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Procedure not found. 
```

Tried with building my own and the prebuilt ones from the CI but get the same results.
Everything seems to work with Valve proton.

**Comment by Tk-Glitch** [comment]
That issue typically happens when the wine prefix was created with an different wine build that isn't compatible with the current one. You might want to delete the prefix for that game so it gets recreated with your current build.

**Comment by shaumux** [comment]
That what my initial thought was as well, didn't work, I proceeded to delete the whole `compadata` directory, and still the same results, and this seems to be happening to all the games and not just one

**Comment by Tk-Glitch** [comment]
Guess I'll have to check that out on a running system. I notice it's 32-bit also. Did you try with a Valve-base build btw? I see you're using a 7.14.r1 build, which might point to some wine upstream change breaking this.

**Comment by shaumux** [comment]
Compiled a Valve Proton and tried with the same result 

```ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
214.136:00c8:00cc:err:module:open_builtin_so_file failed to load .so lib "/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_proton.wine.7.0.3.r0.ga7618abea5f/files/lib/wine/i386-unix/steam.exe.so"
wine: failed to start L"C:\\Program Files (x86)\\Steam\\steam.exe"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Procedure not found.

pid 4759 != 4758, skipping destruction (fork without exec?)
```

Here's the whole file if that helps
[steam-474960.log](https://github.com/Frogging-Family/wine-tkg-git/files/9285334/steam-474960.log)

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue btw, but both https://github.com/Frogging-Family/wine-tkg-git/commit/aedfa6ffd6842f813550160ee4464d342602ee74 and https://github.com/Frogging-Family/wine-tkg-git/commit/fc0580eb2711b0213be3806edb1a9779e07746bd might fix it.

**Comment by shaumux** [comment]
Ok, this was totally my fault I forgot I had to update glibc, the full actual error was only printed in the log once I enabled WINEDEBUG with `
WINEDEBUG=warn+all`

**Comment by Tk-Glitch** [comment]
I'm not sure I understand. Was the issue fixed with a glibc update?

**Comment by shaumux** [comment]
Yes, after the aedfa6ffd6842f813550160ee4464d342602ee74 and fc0580eb2711b0213be3806edb1a9779e07746bd commits I was still having the same problem, so I had to add more debugging and updating glibc fixed the problem, but I can't say for sure that the other commits didn't solve atleast the part of the issue

**Comment by shaumux** [comment]
Just a side note, I had to update glibc to 2.36

**Comment by Tk-Glitch** [comment]
That sounds fine for CI builds (since they are always built against the latest Arch packages), but for the ones built against your own environment, the issue shouldn't exist 🤔

**Comment by shaumux** [comment]
Yeah! but I build inside docker using the arch image and use it on Gentoo

**Comment by Tk-Glitch** [comment]
Ooooh. Makes sense then!

**Comment by shaumux** [comment]
Although previously it would show up in the proton logs f it was a glibc problem, interestingly I had to  `WINEDEBUG=warn+all` this time

**Comment by weter11** [comment]
The same problem, every arch build not working after 7.6.r12 in releases. But builds not working only in Steam, in Lutris everything ok. Also I tried non-Steam games with current git 7.17.r0 with options `NOSTEAM=1 PROTON_LOG=1 %command%` the same error:
`41016.571:0154:0158:err:module:open_builtin_so_file failed to load .so lib "/home/wer/.local/share/Steam/compatibilitytools.d/proton_tkg_7.17.r0.g6d46b1e1/files/lib/wine/i386-unix/steam.exe.so"
wine: failed to start L"C:\\Program Files (x86)\\Steam\\steam.exe"
"`
So I simply replace steam.exe.so from old build, but now only FluidMark, TexMod and Modmanager working in Steam. 32bit and 64bit games not working with different logs. OS: Ubuntu 22.04, also there absent any glibc in my system, so I don't think real problem was in this library.

**Comment by Tk-Glitch** [comment]
> The same problem, every arch build not working after 7.6.r12 in releases. But builds not working only in Steam, in Lutris everything ok. Also I tried non-Steam games with current git 7.17.r0 with options `NOSTEAM=1 PROTON_LOG=1 %command%` the same error: `41016.571:0154:0158:err:module:open_builtin_so_file failed to load .so lib "/home/wer/.local/share/Steam/compatibilitytools.d/proton_tkg_7.17.r0.g6d46b1e1/files/lib/wine/i386-unix/steam.exe.so" wine: failed to start L"C:\\Program Files (x86)\\Steam\\steam.exe" "` So I simply replace steam.exe.so from old build, but now only FluidMark, TexMod and Modmanager working in Steam. 32bit and 64bit games not working with different errors in logs. OS: Ubuntu 22.04, also there absent any glibc in my system, so I don't think real problem was in this library. Little update: with replaced `lsteamclient.dll.so` 32bit games now working, try to find problems with 64.

In the case of non-steam games and apps, you might want to add `PROTON_STANDALONE_START=1` (before `%command%`) to startup options on newer than 7.6.r12 builds.
