### ISSUE TITLE
[Proton-tkg Staging] Last Working Commit for `proton-tkg-staging.patch` is `aabde22`

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#875]
Staging release 7.19 and the two commits prior to it fail to be patched by `proton-tkg-staging.patch`

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/e5c1da3c4a068d0254fcdaa5c872bfb9074e6e35

**Comment by ThisNekoGuy** [comment]
@Tk-Glitch This apparently still an issue with:
https://github.com/wine-staging/wine-staging/commit/41a3c56c5054cf98b2cb443e72ef9728fb025f70
